<a href="https://colab.research.google.com/github/MishelleMurcia26/Analitica-de-Negocios-/blob/main/Naive_Bayes_LavadoActivos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Caso de estudio**
En este docuemnto se desarrolla y analiza un modelo Naive Bayes para la detección de riesgo SARLAFT en una entidad financiera
utilizando las variables del comportamiento financiero y los cambios inusuales en su patrimonio. De acuerdo con lo anterior las variables utilizadas son: Ingresos_usd: Ingresos recibidos de un cliente como resultado de una actividad comercial. Gastos_usd: Son los gastos mensuales del cliente. Gastos de personas a cargo, hijos y servicios publicos. Monto_transado_tarjetas_usd: Indica el dinero que un persona transfiere desde sus tarjetas en dolares.porcentaje_crecimiento_patrimonio: Indica el crecimiento del patrimonio de la cuenta de los clientes en porcentaje.


0.Se procede con la carga de las librerias del trabajo

---



In [ ]:
import numpy as np
import pandas as pd

from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix

1.Se cargan los datos de la base de datos a utilizar

In [ ]:
nxl="/content/2. LavadoActivos.xlsx"
XDB=pd.read_excel(nxl,sheet_name=0)

#Seleccionamos variables de trabajo
XD=XDB[["ingresos_usd","gastos_usd","monto_transado_tarjetas_usd","porcentaje_crecimiento_patrimonio"]] #Variables de trabajo
XD.head(10)
yd=XDB[["lavado_activos"]] #Esta la variable de decision
yd.head()

,lavado_activos
0,1
1,1
2,0
3,0
4,0


2. Implementamos modelo Naive Bayes

In [ ]:
mnb=GaussianNB()
mnb.fit(XD,yd)   #Ajustar Variables Entreda-Salida

#Mostrar las medias de las variables
u=mnb.theta_
sigma=mnb.var_; sigma=np.sqrt(sigma) #Desviacion estandar
print("ingresos_usd","gastos_usd","monto_transado_tarjetas_usd","porcentaje_crecimiento_patrimonio")
print(u)
print("La desviacion estandar es: ")
print(sigma)

ingresos_usd gastos_usd monto_transado_tarjetas_usd porcentaje_crecimiento_patrimonio
[[6.69073255e+03 3.60174970e+03 3.09046404e+03 4.46871435e+01]
 [7.02623043e+04 3.87072844e+04 3.38356197e+04 4.48208630e+01]]
La desviacion estandar es: 
[[6.20696435e+03 3.21901567e+03 2.45685863e+03 1.41731672e+01]
 [1.13412265e+05 6.59025571e+04 6.29913911e+04 1.54786058e+01]]


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


**Analisis de resultados**
De acuerdo con los resultados obtenidos por el modelo, se observa que la categoria de clientes de riesgo posee ingresos mayores que la categoria de clientes sin riesgo, lo que nos indica que los clientes catalogados como de riesgos podrian llegar a tener mas ingresos, y por tanto mayor numero de egresos como se puede observar en los resultados dados.Podemos decir que la parte de montos transados con la tarjeta muestra como los catalogados clientes de riesgo son mas altos que los de no riesgo por su alto indice de movimiento, ya que como miramos en el crecimiento de patrimonio en realidad las dos categorias no tienen mucha variacion



3. Se procede con la evaluacion del modelo. Utilizando la matriz de confusion

In [ ]:
ydp=mnb.predict(XD)
cm=confusion_matrix(yd,ydp)
print(cm)

#Se determina las metricas de la matriz de confusion
VN=cm[0,0]; FP=cm[0,1]; FN=cm[1,0]; VP=cm[1,1];TDatos=len(XDB)

#1. Exactitud: Funcionamiento general del modelo
EX=(VP+VN)/TDatos
print("Exactitud: ",EX)

#2. Tasa Error: %Fallos del modelo
TEr=(FP+FN)/TDatos
print("Tasa Error: ",TEr)

#3. Sensibilidad: Como se comporto con respecto a los positivos solamente
Se=VP/(VP+FN)
print("Sensibilidad: ",Se)

#4. Especificidad: Como se comporta pronosticando negativos
Es=VN/(VN+FP)
print("Especificidad: ",Es)

#5. Precision: Es una version de como se comporta el modelo frente a los positivos solamente
Pr=VP/(VP+FP)
print("Precision: ",Pr)

#6. Prediccion negativa: Como funciona el modelo pronosticando acciones extrañas
PrN=VN/(VN+FN)
print("Prediccion Negativa: ",PrN)


[[2179   44]
 [ 142  785]]
Exactitud:  0.940952380952381
Tasa Error:  0.05904761904761905
Sensibilidad:  0.8468176914778857
Especificidad:  0.9802069275753487
Precision:  0.9469240048250904
Prediccion Negativa:  0.9388194743644981


**Analisis de resultados**
De acuerdo con los resultados obtenidos por el modelo, se observa que le modelo alcanzo un 94% de exactitud,lo que indica un excelente comportamiento del modelo frente a a clasificaion de posibles clientes de riesgo. Se destaca una tasa de error de solo el 0.6%, mostrandonos una efectividad casi perfecta del modelo en la clasificacion de clientes de riesgo y clientes sin riesgo. De igual manera, se puede observar el buen comportamiento del modelo frente a la clasificaion de clientes sin riesgo, tal y como lo demuestra el indice de especificidad del modelo, el cual estuvo por encima 98%. Es importante mencionar que la exactitud queda por debajo del 85% ya que esta metrica se ve afectada por los errores en la clasificacion de riesgos de los clientes, lo que se evidencia a traves de las sensibilidad

4. Evaluamos un cliente

In [ ]:
XP=[17,4000,9000,80000]
ydc=mnb.predict([XP])
print("La clasificacion del cliente es: ",ydc)

if ydc==1:
  print("El cliente presenta incongruencia en la cuenta-Es un cliente de riesgo")
else:
  print("El cliente presenta todo en normalidad-Es un cliente sin riesgo")

La clasificacion del cliente es:  [1]
El cliente presenta incongruencia en la cuenta-Es un cliente de riesgo


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(
